apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverse-proxy
  labels:
    app: udagram-reverse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverse-proxy
  template:
    metadata:
      labels:
        app: udagram-reverse-proxy
    spec:
      containers:
      - name: image-udagram-reverseproxy
        image: nacojohn/udagram-reverseproxy:v3
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 